import type { Metadata } from "next";
import "../src/app/globals.css";

export const metadata: Metadata = {
  title: "DocuMate",
  description: "Generated by DocuMate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
